version: "3.9"

services:
  nextjsfagkveld:
    # Specify the image to start the container from
    #image: node:18.13.0-alpine
    container_name: nextjsfagkveld
    # Bygg fra Dockerfile, allows installs to be run
    build:
      context: .
      dockerfile: Dockerfile

    tty: true

    # Expose ports (HOST:CONTAINER)
    ports:
      - 3000:3000
      
    # Set environment variables
    #environment:

    # Mount host directories to container directories
    volumes:
      - ./source:/source
      - npm-volume:/source/node_modules

volumes:
  npm-volume: