version: "3"

services:
  nextjsbasics:
    build:
      context: .
      dockerfile: ./nextjs-basics/Dockerfile
    container_name: basics
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  nextjsfrontend:
    build:
      context: .
      dockerfile: ./nextjs-frontend/Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3001:3001
  nextjsapi:
    build:
      context: .
      dockerfile: ./nextjs-frontend/Dockerfile
    container_name: api
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3050:3050