version: "3"

services:
  nextjsfagkveld:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjsapi
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3050:3050